$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: data-register-experiment
display_name: data-register-pipeline

jobs:
  register_data:
    code: script_folder
    command: python data-register.py --data_path
    environment: azureml:train-env@latest
    compute: azureml:ml-cluster
